import Head from 'next/head';
import { Poppins } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import CountDown from '@/sections/Home/CountDown';


const poppins = Poppins({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.className}`}>
        <Navbar/>
        <CountDown duration={10000}/>

        <div className='h-20 w-40 orange-gradient'>
          hwloo
        </div>
        <Footer/>
      </main>
    </>
  );
}
