import Head from 'next/head';
import { Poppins } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import CountDown from '@/sections/Home/CountDown';
import Hero from '@/sections/Home/Hero';
import HowToMint from '@/sections/Home/HowToMint';
import AboutDrop from '@/sections/Home/AboutDrop';
import RoadMap from '@/sections/Home/RoadMap';
import OurTeam from '@/sections/Home/OurTeam';



const poppins = Poppins({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.className} bg-white text-black`}>
        <Navbar/>
        <Hero/>
        <CountDown duration={122545}/>
        <HowToMint/>
        <AboutDrop/>
        <RoadMap/>
        <OurTeam/>
        <Footer/>
      </main>
    </>
  );
}
