import React from 'react';
import Head from 'next/head';
import Layout from '@/components/Layout';
import Hero from '@/sections/Landing2/Hero';
import AboutGame from '@/sections/Landing2/AboutGame';
import ShowCase from '@/sections/Landing2/ShowCase';
import OurGallery from '@/sections/Landing2/OurGallery';
const landingTwo = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="text-black pt-24">
          <Hero />
          <AboutGame />
          <ShowCase />
          <OurGallery />
        </div>
      </Layout>
    </>
  );
};

export default landingTwo;
